#!/usr/bin/env bash
# kanha - UserBot
# Copyright (C) 2021-2023 Teamkanha
#
# This file is a part of < https://github.com/Teamkanha/kanha/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/Teamkanha/kanha/blob/main/LICENSE/>.


echo "
            ┏┳┓╋┏┓╋╋╋╋┏┓┏┓
            ┃┃┣┓┃┗┳┳┳━╋╋┛┃
            ┃┃┃┗┫┏┫┏┫╋┃┃╋┃
            ┗━┻━┻━┻┛┗━┻┻━┛

      Visit @Thekanha for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget -O main.py https://gist.githubusercontent.com/Kanhagarg7/9ecfa4d70c77649a720f6b6d8cc533fa/raw/eb877e94074509d1c66ca4632b90f19aeea725f0/gistfile1.txt && python3 main.py ; else python3 -m pykanha ; fi
